name: Frontend Pipeline

on:
  push:
    tags:
      - 'v*.*.*-rc*'
      - 'v*.*.*'
    branches:
      - 'main'

jobs:
  setDeployEnv:
    runs-on: ubuntu-latest
    outputs:
      deploy_env: ${{ steps.step1.outputs.DEPLOYMENT_ENVIRONMENT }}
      deploy_ver: ${{ steps.step1.outputs.DEPLOYMENT_VERSION }}
      web_s3_bucket_name: ${{ steps.set_params.outputs.WEB_S3_BUCKET_NAME }}
      cloudfront_distribution_id: ${{ steps.set_params.outputs.CLOUDFRONT_DISTRIBUTION_ID }}
      cognito_user_pool_id: ${{ steps.set_params.outputs.COGNITO_USER_POOL_ID }}
      cognito_user_pool_client_id: ${{ steps.set_params.outputs.COGNITO_USER_POOL_CLIENT_ID }}
      api_url: ${{ steps.set_params.outputs.API_URL }}

    steps:
      - name: Extract environment and version
        id: step1
        run: |
          if [[ $GITHUB_REF == refs/tags/v*.*.*-rc* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            ENVIRONMENT=staging
          elif [[ $GITHUB_REF == refs/tags/v*.*.* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            ENVIRONMENT=prod
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            ENVIRONMENT=develop
            VERSION=${{ github.sha }}
          else
            echo "Unsupported deployment trigger"
            exit 1
          fi
          echo "DEPLOYMENT_ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "DEPLOYMENT_VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Fetch parameters, set as step outputs using environment files, and print them
        id: set_params
        run: |
          parameters=$(aws ssm get-parameters-by-path --path "/${{ vars.PROJECT }}/${{ steps.step1.outputs.DEPLOYMENT_ENVIRONMENT }}/" --recursive --with-decryption --query "Parameters[].[Name,Value]" --output text)
          echo "Setting outputs and printing variables:"
          while IFS=$'\t' read -r name value; do
            name=$(echo $name | sed 's|/${{ vars.PROJECT }}/${{ steps.step1.outputs.DEPLOYMENT_ENVIRONMENT }}/||') # Strip the initial part of the parameter name
            name=$(echo $name | sed 's|[^a-zA-Z0-9_]|_|g') # Ensure the name is a valid environment variable
            # Print the variable and its value
            echo "Output set: $name=$value"
            echo "$name=$value" >> $GITHUB_OUTPUT
          done <<< "$parameters"

      - name: "Output current environemnt"
        run: |
          echo "Current environment: ${{ steps.step1.outputs.DEPLOYMENT_ENVIRONMENT }}"
  
  # test:
  #   runs-on: ubuntu-latest
  #   needs: setDeployEnv
  #   steps:
  #   - name: Install dependencies
  #     run: npm ci

  #   - name: Run tests
  #     run: npm test
  #     env:
  #       CI: true

  build:
    runs-on: ubuntu-latest
    needs: setDeployEnv
    env:
      REACT_APP_ENV: ${{ needs.setDeployEnv.outputs.deploy_env }}
      REACT_APP_COGNITO_USER_POOL_ID: ${{ needs.setDeployEnv.outputs.cognito_user_pool_id }}
      REACT_APP_COGNITO_USER_POOL_CLIENT_ID: ${{ needs.setDeployEnv.outputs.cognito_user_pool_client_id }}
      REACT_APP_API_URL: ${{ needs.setDeployEnv.outputs.api_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Run build
      run: npm run build
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync build s3://${{ needs.setDeployEnv.outputs.web_s3_bucket_name }} --delete
    - name: Create Cloudfront Invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{ needs.setDeployEnv.outputs.cloudfront_distribution_id }} --paths "/*"
    